// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ContractClientProgram;
impl sails_rs::client::Program for ContractClientProgram {}
pub trait ContractClient {
    type Env: sails_rs::client::GearEnv;
    fn contract_svc(&self) -> sails_rs::client::Service<contract_svc::ContractSvcImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ContractClient
    for sails_rs::client::Actor<ContractClientProgram, E>
{
    type Env = E;
    fn contract_svc(&self) -> sails_rs::client::Service<contract_svc::ContractSvcImpl, Self::Env> {
        self.service(stringify!(ContractSvc))
    }
}
pub trait ContractClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn init(self) -> sails_rs::client::PendingCtor<ContractClientProgram, io::Init, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ContractClientCtors
    for sails_rs::client::Deployment<ContractClientProgram, E>
{
    type Env = E;
    fn init(self) -> sails_rs::client::PendingCtor<ContractClientProgram, io::Init, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Init () -> ());
}

pub mod contract_svc {
    use super::*;
    pub trait ContractSvc {
        type Env: sails_rs::client::GearEnv;
        fn decrement(&mut self) -> sails_rs::client::PendingCall<io::Decrement, Self::Env>;
        /// #[returns_value]
        fn get_value(
            &mut self,
            to_return: u128,
        ) -> sails_rs::client::PendingCall<io::GetValue, Self::Env>;
        fn greet(&mut self) -> sails_rs::client::PendingCall<io::Greet, Self::Env>;
        fn increment(&mut self) -> sails_rs::client::PendingCall<io::Increment, Self::Env>;
        /// #[payable]
        fn send_value(&mut self) -> sails_rs::client::PendingCall<io::SendValue, Self::Env>;
        fn contract_total_eth(
            &self,
        ) -> sails_rs::client::PendingCall<io::ContractTotalEth, Self::Env>;
        fn counter_value(&self) -> sails_rs::client::PendingCall<io::CounterValue, Self::Env>;
    }
    pub struct ContractSvcImpl;
    impl<E: sails_rs::client::GearEnv> ContractSvc for sails_rs::client::Service<ContractSvcImpl, E> {
        type Env = E;
        fn decrement(&mut self) -> sails_rs::client::PendingCall<io::Decrement, Self::Env> {
            self.pending_call(())
        }
        fn get_value(
            &mut self,
            to_return: u128,
        ) -> sails_rs::client::PendingCall<io::GetValue, Self::Env> {
            self.pending_call((to_return,))
        }
        fn greet(&mut self) -> sails_rs::client::PendingCall<io::Greet, Self::Env> {
            self.pending_call(())
        }
        fn increment(&mut self) -> sails_rs::client::PendingCall<io::Increment, Self::Env> {
            self.pending_call(())
        }
        fn send_value(&mut self) -> sails_rs::client::PendingCall<io::SendValue, Self::Env> {
            self.pending_call(())
        }
        fn contract_total_eth(
            &self,
        ) -> sails_rs::client::PendingCall<io::ContractTotalEth, Self::Env> {
            self.pending_call(())
        }
        fn counter_value(&self) -> sails_rs::client::PendingCall<io::CounterValue, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Decrement () -> u64);
        sails_rs::io_struct_impl!(GetValue (to_return: u128) -> String);
        sails_rs::io_struct_impl!(Greet () -> String);
        sails_rs::io_struct_impl!(Increment () -> u64);
        sails_rs::io_struct_impl!(SendValue () -> String);
        sails_rs::io_struct_impl!(ContractTotalEth () -> u128);
        sails_rs::io_struct_impl!(CounterValue () -> u64);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum ContractSvcEvents {
            Hello([u8; 20]),
            ValueReceived(u128),
            ValueSent(u128),
            Incremented,
            Decremented,
        }
        impl sails_rs::client::Event for ContractSvcEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "Hello",
                "ValueReceived",
                "ValueSent",
                "Incremented",
                "Decremented",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for ContractSvcImpl {
            type Event = ContractSvcEvents;
        }
    }
}
